### ISSUE TITLE
Notice: Trying to get property 'data' of non-object

### ISSUE THREAD

**Issue by mudrd8mz** [anayleeloolxp/moodle-tool_leeloolxp_sync#1]
Attempting to enrol a user via `mdk` started to throw following:

    Notice: Trying to get property 'data' of non-object in .../admin/tool/leeloolxp_sync/classes/syncobserver.php on line 399

Ref: https://docs.moodle.org/dev/Plugin_contribution_checklist#Functionality

**Comment by anayleeloolxp** [comment]
Hello @mudrd8mz, thanks for informing about this notice. Have fixed it in the new release.
